### ISSUE TITLE
Container will not start

### ISSUE THREAD

**Issue by PaRkThEcAr** [clickbg/homekit-monitord#1]
Platform: macOS 12.3.1

Logs
```/etc/monit/monitrc:13: missing address ''
Restarting daemon monitor: monit failed!
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/99-homekit-monitoring-config.sh
/etc/monit/monitrc:13: missing address ''
Restarting daemon monitor: monit failed!
```

Configuration 

```
version: '3.6'
services:

  homekit-monitord:
    container_name: homekit-monitord
    restart: always
    image: clickbg/homekit-monitord:latest
    ports:
      - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
      - RESTART_HUB=0
      - HOMEKIT_HUBS=192.168.1.20:200 192.168.1.21:200 192.168.1.22:200 192.168.1.25:200 192.168.1.27:200 192.168.1.28:200
      - TELEGRAM_TOKEN=SUPERSECRET
      - TELEGRAM_CHATID=SECRET
    healthcheck:
      test: curl --fail http://localhost/nginx_status || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
```

I cant seem to get the container to start
