### ISSUE TITLE
Telegram notification fails.

### ISSUE THREAD

**Issue by PaRkThEcAr** [clickbg/homekit-monitord#12]
hey there! first, some logs. 

```
homekit-monitord  | 172.18.0.1 - - [20/May/2022:14:23:53 -0600] "GET /active-hub-report-health/ HTTP/1.1" 200 44 "-" "BackgroundShortcutRunner/1146.14 CFNetwork/1333.0.4 Darwin/21.5.0" "-"

homekit-monitord  | [2022-05-20T14:33:31-0600] info     : '647c80d371fa' Monit 5.27.2 started

homekit-monitord  | 2022-05-20 14:33:31 [SUCCESS] HomeKit Active Hub [172.18.0.1] successfully reported state on [2022-05-20T14:23:53-06:00] which is less than [10min] ago

homekit-monitord  | 2022-05-20 14:43:31 [FAILED] HomeKit Active Hub [172.18.0.1] last reported state on [2022-05-20T14:23:53-06:00] which is more than [10min] ago
```

here is the config

```
version: '3.6'   
services:
      
  homekit-monitord:
    container_name: homekit-monitord
    restart: always
    image: clickbg/homekit-monitord:latest
    ports:
      - "8080:80"
    environment:   
      - PUID=1000
      - PGID=1000
      - RESTART_HUB=0
      - TZ=America/Denver
      - HOMEKIT_HUBS=HUBIP'S
      - TELEGRAM_TOKEN=5XXXXXXXXXXXXXXXXX_XXXXXXXX
      - TELEGRAM_CHATID=1XXXXXXXX
    healthcheck:
      test: curl --fail http://localhost/nginx_status || exit 1
      interval: 10s
      retries: 1
      start_period: 5s
      timeout: 10s
```

what i am curious on is why i dont get the notification nor any notice that it failed. is there any toubleshooting you recomend? i verified the ChatID and the Token.
